#[derive(Clone, Debug, num_enum::FromPrimitive, num_enum::IntoPrimitive)]
#[repr(u32)]
pub enum Term {
    /// - %S = Enemy name
    EnemyAppeared = 1,
    PreemptiveAttack = 2,
    EscapedSuccessfully = 3,
    FailedToEscape = 4,
    BattleWon = 5,
    BattleLost = 6,
    /// - %V = Value
    /// - %U = Unit
    ExperienceEarned = 7,
    /// - %V = Value
    /// - %U = Unit
    MoneyObtained = 8,
    /// - %S = Item name
    ItemObtained = 10,
    /// - %S = Attacker name
    NormalAttack = 11,
    /// - %S = Attacker
    /// - %O = Target
    CriticalHitOnActor = 12,
    /// - %S = Attacker
    /// - %O = Target
    CriticalHitOnEnemy = 13,
    /// - %S = Actor/enemy name
    Defending = 14,
    /// - %S = Enemy name
    Waiting = 15,
    /// - %S = Enemy name
    Charging = 16,
    /// - %S = Enemy name
    SelfDestructing = 17,
    /// - %S = Enemy name
    EnemyEscape = 18,
    /// - %S = Old name
    /// - %O = New name
    EnemyTransform = 19,

    /// - %S = Enemy
    /// - %V = Value
    /// - %U = Unit
    EnemyHurt = 20,
    /// - %S = Enemy name
    EnemyNotHurt = 21,
    /// - %S = Actor
    /// - %V = Value
    /// - %U = Unit
    ActorHurt = 22,
    /// - %S = Actor name
    ActorNotHurt = 23,
    /// - %S = Attacker
    /// - %O = Target
    SpecialSkillAFailed = 24,
    /// - %S = Attacker
    /// - %O = Target
    SpecialSkillBFailed = 25,
    /// - %S = Attacker
    /// - %O = Target
    SpecialSkillCFailed = 26,
    /// - %S = Attacker
    /// - %O = Target
    PhyiscalAttackMissed = 27,
    /// - %S = Actor name
    /// - %O = Item name
    ItemUsed = 28,
    /// - %S = Target
    /// - %V = Value
    /// - %U = Stat
    HPMPRecovery = 29,
    /// - %S = Target
    /// - %V = Value
    /// - %U = Stat
    StatIncreased = 30,
    /// - %S = Target
    /// - %V = Value
    /// - %U = Stat
    StatDecreased = 31,
    /// - %S = Attacker
    /// - %O = Target
    /// - %V = Value?
    /// - %U = Unit?
    HPMPAbsorbFromEnemy = 32,
    /// - %S = Attacker
    /// - %O = Target
    /// - %V = Value?
    /// - %U = Unit?
    HPMPAbsorbFromActor = 33,
    /// - %S = Target
    /// - %O = Element
    ElementUp = 34,
    /// - %S = Target
    /// - %O = Element
    ElementDown = 35,
    /// - %S = Actor name
    /// - %V = New level
    /// - %U = Unit
    LevelUp = 36,
    /// - %S = Actor name
    /// - %O = Skill name
    NewSkillLearned = 37,

    ShopAChooseAction = 41,
    ShopAChooseActionAgain = 42,
    ShopABuy = 43,
    ShopASell = 44,
    ShopACancel = 45,
    ShopAPurchasingItem = 46,
    ShopANumberOfPurchasedItems = 47,
    ShopAPurchaseCompleted = 48,
    ShopASellingItem = 49,
    ShopANumberOfSoldItems = 50,
    ShopATransactionComplete = 51,
    ShopBChooseAction = 54,
    ShopBChooseActionAgain = 55,
    ShopBBuy = 56,
    ShopBSell = 57,
    ShopBCancel = 58,
    ShopBPurchasingItem = 59,
    ShopBNumberOfPurchasedItems = 60,
    ShopBPurchaseCompleted = 61,
    ShopBSellingItem = 62,
    ShopBNumberOfSoldItems = 63,
    ShopBTransactionComplete = 64,

    ShopCChooseAction = 67,
    ShopCChooseActionAgain = 68,
    ShopCBuy = 69,
    ShopCSell = 70,
    ShopCCancel = 71,
    ShopCPurchasingItem = 72,
    ShopCNumberOfPurchasedItems = 73,
    ShopCPurchaseCompleted = 74,
    ShopCSellingItem = 75,
    ShopCNumberOfSoldItems = 76,
    ShopCTransactionComplete = 77,
    /// - %V = Value
    /// - %U = Unit
    InnAChoice1 = 80,
    /// - %V = Value
    /// - %U = Unit
    InnAChoice2 = 82,
    InnAStay = 83,
    InnALeave = 84,
    /// - %V = Value
    /// - %U = Unit
    InnBChoice1 = 85,
    /// - %V = Value
    /// - %U = Unit
    InnBChoice2 = 87,
    InnBStay = 88,
    InnBLeave = 89,
    Posession = 92,
    Equipped = 93,
    Currency = 94,

    Fight = 101,
    Autobattle = 102,
    Escape = 103,
    BattleAttack = 104,
    Defend = 105,
    Items = 106,
    Skills = 107,
    Equipment = 108,
    Save = 110,
    EndGame = 112,
    NewGame = 114,
    Continue = 115,
    Shutdown = 117,
    Level = 123,
    HP = 124,
    MP = 125,
    Normal = 126,
    ExperienceAbbr = 127,
    LevelAbbr = 128,
    HPAbbr = 129,
    MPAbbr = 130,
    MPCost = 131,
    AttackStat = 132,
    Defense = 133,
    Mind = 134,
    Agility = 135,
    Weapon = 136,
    Shield = 137,
    Body = 138,
    Head = 139,
    Accessory = 140,
    ChooseFileToSave = 146,
    ChooseFileToLoad = 147,
    ChooseSaveFile = 148,
    EndGameConfirmation = 149,
    Yes = 152,
    No = 153,

    #[num_enum(catch_all)]
    Unknown(u32),
}
